# Nginx Proxy Manager
services:
    npmapp:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
        - '80:80'
        - '127.0.0.1:81:81'
        - '443:443'
        volumes:
            - ./volumes/npm/data:/data
            - ./volumes/npm/letsencrypt:/etc/letsencrypt

